import { Exercise } from '../types';
import { AsmInstruction } from '@/engine/x86/types';

const instructions: AsmInstruction[] = [
  { addr: 0x08048000, bytes: [0x55], mnemonic: 'push', operands: 'ebp', comment: 'Prologue: save old frame pointer' },
  { addr: 0x08048001, bytes: [0x89, 0xe5], mnemonic: 'mov', operands: 'ebp, esp', comment: 'Prologue: set new frame pointer' },
  { addr: 0x08048003, bytes: [0x83, 0xec, 0x10], mnemonic: 'sub', operands: 'esp, 16', comment: 'Prologue: allocate space for locals' },
  { addr: 0x08048006, bytes: [0xc7, 0x45, 0xfc, 0x0a, 0x00, 0x00, 0x00], mnemonic: 'mov', operands: '[ebp-4], 10', comment: 'Store local variable x' },
  { addr: 0x0804800d, bytes: [0xc7, 0x45, 0xf8, 0x14, 0x00, 0x00, 0x00], mnemonic: 'mov', operands: '[ebp-8], 20', comment: 'Store local variable y' },
  { addr: 0x08048014, bytes: [0x8b, 0x45, 0xfc], mnemonic: 'mov', operands: 'eax, [ebp-4]', comment: 'Load x into EAX' },
  { addr: 0x08048017, bytes: [0x03, 0x45, 0xf8], mnemonic: 'add', operands: 'eax, [ebp-8]', comment: 'Add y to EAX' },
  { addr: 0x0804801a, bytes: [0xc9], mnemonic: 'leave', operands: '', comment: 'Epilogue: restore frame' },
  { addr: 0x0804801b, bytes: [0xf4], mnemonic: 'hlt', operands: '', comment: '' },
];

export const asm09: Exercise = {
  id: 'asm-09',
  unitId: 'unit0-asm',
  title: 'Stack Frames',
  desc: '<b>Goal:</b> Understand the function prologue and epilogue — the setup and teardown of every function\'s stack frame. <b>Prologue:</b> push ebp; mov ebp,esp; sub esp,N. <b>Epilogue:</b> leave (= mov esp,ebp; pop ebp). Local variables live at negative offsets from EBP.',
  source: {
    c: [
      { text: '// Stack Frame Layout', cls: 'comment' },
      { text: '//   [ebp+8]  → first argument', cls: 'comment' },
      { text: '//   [ebp+4]  → return address', cls: 'comment' },
      { text: '//   [ebp]    → saved EBP', cls: 'comment' },
      { text: '//   [ebp-4]  → first local variable', cls: 'comment' },
      { text: '//   [ebp-8]  → second local variable', cls: 'comment' },
      { text: '', cls: '' },
      { text: '// C equivalent:', cls: 'comment' },
      { text: '// void func() {', cls: 'comment' },
      { text: '//   int x = 10, y = 20;', cls: 'comment' },
      { text: '//   return x + y;', cls: 'comment' },
      { text: '// }', cls: 'comment' },
      { text: '', cls: '' },
      { text: '; — Prologue —', cls: 'label' },
      { text: 'push ebp          ; save old frame', cls: 'asm' },
      { text: 'mov ebp, esp      ; new frame pointer', cls: 'asm' },
      { text: 'sub esp, 16       ; space for locals', cls: 'asm' },
      { text: '', cls: '' },
      { text: 'mov [ebp-4], 10   ; x', cls: 'asm' },
      { text: 'mov [ebp-8], 20   ; y', cls: 'asm' },
      { text: 'mov eax, [ebp-4]', cls: 'asm' },
      { text: 'add eax, [ebp-8]', cls: 'asm' },
      { text: '', cls: '' },
      { text: '; — Epilogue —', cls: 'label' },
      { text: 'leave             ; restore frame', cls: 'asm' },
      { text: 'hlt', cls: 'asm' },
    ],
  },
  mode: 'asm-quiz',
  vizMode: 'asm',
  asmInstructions: instructions,
  asmQuiz: [
    { question: 'What is EAX at the end (x + y)?', answer: 30, format: 'decimal', hint: 'x = 10 at [ebp-4], y = 20 at [ebp-8]. 10 + 20 = 30.' },
    { question: 'How many bytes does "sub esp, 16" allocate for locals?', answer: 16, format: 'decimal', hint: 'The prologue reserves stack space by subtracting from ESP.' },
  ],
  check: () => false,
  winTitle: 'Stack Frames Mastered!',
  winMsg: 'You understand prologue/epilogue — the structure that buffer overflows target.',
};
