import { Exercise } from '../types';
import { AsmInstruction } from '@/engine/x86/types';

const instructions: AsmInstruction[] = [
  { addr: 0x08048000, bytes: [0x55], mnemonic: 'push', operands: 'ebp', comment: 'main prologue' },
  { addr: 0x08048001, bytes: [0x89, 0xe5], mnemonic: 'mov', operands: 'ebp, esp', comment: '' },
  { addr: 0x08048003, bytes: [0x6a, 0x03], mnemonic: 'push', operands: '3', comment: 'Push arg2 (right-to-left order)' },
  { addr: 0x08048005, bytes: [0x6a, 0x05], mnemonic: 'push', operands: '5', comment: 'Push arg1' },
  { addr: 0x08048007, bytes: [0xe8, 0x08, 0x00, 0x00, 0x00], mnemonic: 'call', operands: '0x08048014', comment: 'Call add_nums' },
  { addr: 0x0804800c, bytes: [0x83, 0xc4, 0x08], mnemonic: 'add', operands: 'esp, 8', comment: 'Who is cleaning up here?' },
  { addr: 0x0804800f, bytes: [0x89, 0xc3], mnemonic: 'mov', operands: 'ebx, eax', comment: 'Save return value' },
  { addr: 0x08048011, bytes: [0xc9], mnemonic: 'leave', operands: '', comment: '' },
  { addr: 0x08048012, bytes: [0xf4], mnemonic: 'hlt', operands: '', comment: '' },
  { addr: 0x08048014, bytes: [0x55], mnemonic: 'push', operands: 'ebp', comment: 'add_nums prologue' },
  { addr: 0x08048015, bytes: [0x89, 0xe5], mnemonic: 'mov', operands: 'ebp, esp', comment: '' },
  { addr: 0x08048017, bytes: [0x8b, 0x45, 0x08], mnemonic: 'mov', operands: 'eax, [ebp+8]', comment: 'Load first argument' },
  { addr: 0x0804801a, bytes: [0x03, 0x45, 0x0c], mnemonic: 'add', operands: 'eax, [ebp+12]', comment: 'Add second argument' },
  { addr: 0x0804801d, bytes: [0xc9], mnemonic: 'leave', operands: '', comment: '' },
  { addr: 0x0804801e, bytes: [0xc3], mnemonic: 'ret', operands: '', comment: '' },
];

export const asm10: Exercise = {
  id: 'asm-10',
  unitId: 'unit0-asm',
  title: 'Calling Conventions',
  desc: '<b>Goal:</b> See the <b>cdecl</b> calling convention in action. Arguments pushed right-to-left, <b>caller</b> cleans the stack, return value in <b>EAX</b>. Arguments are at [ebp+8], [ebp+12], etc. (past saved EBP at [ebp] and return address at [ebp+4]).',
  source: {
    c: [
      { text: '// cdecl Calling Convention', cls: 'comment' },
      { text: '// 1. Args pushed right → left', cls: 'comment' },
      { text: '// 2. CALLER cleans stack after call', cls: 'comment' },
      { text: '// 3. Return value in EAX', cls: 'comment' },
      { text: '// 4. EAX, ECX, EDX are caller-saved', cls: 'comment' },
      { text: '// 5. EBX, ESI, EDI are callee-saved', cls: 'comment' },
      { text: '', cls: '' },
      { text: '// int add_nums(int a, int b) {', cls: 'comment' },
      { text: '//   return a + b;', cls: 'comment' },
      { text: '// }', cls: 'comment' },
      { text: '// int main() {', cls: 'comment' },
      { text: '//   int result = add_nums(5, 3);', cls: 'comment' },
      { text: '// }', cls: 'comment' },
      { text: '', cls: '' },
      { text: 'main:', cls: 'label' },
      { text: '  push ebp / mov ebp, esp', cls: 'asm' },
      { text: '  push 3           ; arg2', cls: 'asm' },
      { text: '  push 5           ; arg1', cls: 'asm' },
      { text: '  call add_nums', cls: 'asm' },
      { text: '  add esp, 8', cls: 'asm' },
      { text: '  mov ebx, eax', cls: 'asm' },
      { text: '  leave / hlt', cls: 'asm' },
      { text: '', cls: '' },
      { text: 'add_nums:', cls: 'label' },
      { text: '  push ebp / mov ebp, esp', cls: 'asm' },
      { text: '  mov eax, [ebp+8]', cls: 'asm' },
      { text: '  add eax, [ebp+12]', cls: 'asm' },
      { text: '  leave / ret', cls: 'asm' },
    ],
  },
  mode: 'asm-quiz',
  vizMode: 'asm',
  asmInstructions: instructions,
  asmQuiz: [
    { question: 'What is EAX after add_nums(5, 3) returns?', answer: 8, format: 'decimal', hint: 'The function adds its two arguments: 5 + 3 = 8.' },
    { question: 'In cdecl, who cleans arguments from the stack — caller or callee? (1=caller, 2=callee)', answer: 1, format: 'decimal', hint: 'Look at "add esp, 8" after the call — that is the CALLER removing arguments.' },
  ],
  check: () => false,
  winTitle: 'Calling Convention Expert!',
  winMsg: 'You understand cdecl — how C functions pass arguments via the stack.',
};
